# Week 10
## Pre-Class Activity

In [13]:
import numpy as np
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

[2. 3.]


In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
print(a.shape)
print(b.shape)
print(x.shape)

(2, 2)
(2,)
(2,)


In [16]:
a1 = a[1,:]
print(a1, a1.shape)
a2 = a[:,1]
print(a2, a2.shape)

[1 2] (2,)
[1 2] (2,)


In [17]:
ls = [1]
a3 = a[ls,:]
print(a3, a3.shape)
a4 = a[:,ls]
print(a4, a4.shape)

[[1 2]] (1, 2)
[[1]
 [2]] (2, 1)


In [18]:
b1 = b.reshape(1, b.size) #now b1 is a 1 by n 2D array
print(b1)
b2 = b.reshape(b.size, 1) #now b2 is a n by 1 2D array
print(b2)

[[9 8]]
[[9]
 [8]]


In [19]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
bunchobject = datasets.load_breast_cancer()

In [20]:
print(bunchobject.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [21]:
print(bunchobject.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [22]:
print(bunchobject.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [23]:
print(bunchobject.target_names)
print(bunchobject.data.shape)

['malignant' 'benign']
(569, 30)


In [24]:
column_index = [1]
print(bunchobject.feature_names[column_index])
feature_vals_in_column = bunchobject.data[:,column_index]
print(feature_vals_in_column)
print( np.min(feature_vals_in_column), np.max(feature_vals_in_column))

['mean texture']
[[10.38]
 [17.77]
 [21.25]
 [20.38]
 [14.34]
 [15.7 ]
 [19.98]
 [20.83]
 [21.82]
 [24.04]
 [23.24]
 [17.89]
 [24.8 ]
 [23.95]
 [22.61]
 [27.54]
 [20.13]
 [20.68]
 [22.15]
 [14.36]
 [15.71]
 [12.44]
 [14.26]
 [23.04]
 [21.38]
 [16.4 ]
 [21.53]
 [20.25]
 [25.27]
 [15.05]
 [25.11]
 [18.7 ]
 [23.98]
 [26.47]
 [17.88]
 [21.59]
 [21.72]
 [18.42]
 [25.2 ]
 [20.82]
 [21.58]
 [21.35]
 [24.81]
 [20.28]
 [21.81]
 [17.6 ]
 [16.84]
 [18.66]
 [14.63]
 [22.3 ]
 [21.6 ]
 [16.34]
 [18.24]
 [18.7 ]
 [22.02]
 [18.75]
 [18.57]
 [21.59]
 [19.31]
 [11.79]
 [14.88]
 [20.98]
 [22.15]
 [13.86]
 [23.84]
 [23.94]
 [21.01]
 [19.04]
 [17.33]
 [16.49]
 [21.31]
 [14.64]
 [24.52]
 [15.79]
 [16.52]
 [19.65]
 [10.94]
 [16.15]
 [23.97]
 [18.  ]
 [20.97]
 [15.86]
 [24.91]
 [26.29]
 [15.65]
 [18.52]
 [21.46]
 [24.59]
 [21.8 ]
 [15.24]
 [24.02]
 [22.76]
 [14.76]
 [18.3 ]
 [19.83]
 [23.03]
 [17.84]
 [19.94]
 [12.84]
 [19.77]
 [24.98]
 [13.43]
 [20.52]
 [19.4 ]
 [19.29]
 [15.56]
 [18.33]
 [18.54]
 [19.67]
 [

In [25]:
row_index = [1]
print(bunchobject.feature_names)
record_vals_in_row = bunchobject.data[row_index,:]
print(record_vals_in_row)
print(bunchobject.target[row_index])

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
[[2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]]
[0]


In [26]:
unique, counts = np.unique(bunchobject.target, return_counts = True)
for i in unique:
    print(i, bunchobject.target_names[i], counts[i])

0 malignant 212
1 benign 357


## Cohort Problems
### Problem 1

In [31]:
import numpy as np
from sklearn.metrics import confusion_matrix
def get_metrics(actual_targets, predicted_targets, labels):
    dictionary = {}
    c_matrix = confusion_matrix(actual_targets, predicted_targets,labels)
    dictionary['confusion matrix'] = c_matrix
    dictionary['total records'] = np.sum(dictionary['confusion matrix'])
    dictionary['accuracy'] = (c_matrix[0,0] + c_matrix[1,1])/np.sum(c_matrix)
    dictionary['sensitivity'] = c_matrix[1,1]/np.sum(c_matrix[[1],:])
    dictionary['false positive rate'] = c_matrix[0,1]/np.sum(c_matrix[[0],:])
    return dictionary

actual = ['cat', 'cat', 'cat', 'cat', 'bird', 'bird','bird','bird']
predicted = ['cat', 'cat', 'bird', 'bird', 'cat', 'bird', 'bird', 'bird']
labels = ['bird', 'cat']
print(get_metrics(actual, predicted, labels))

{'confusion matrix': array([[3, 1],
       [2, 2]]), 'total records': 8, 'accuracy': 0.625, 'sensitivity': 0.5, 'false positive rate': 0.25}


### Problem 2

In [28]:
def five_number_summary(x):
    summary={}
    summary['minimum'] = np.min(x)
    summary['first quartile'] = np.percentile(x,25)
    summary['median'] = np.percentile(x,50)
    summary['third quartile'] = np.percentile(x,75)
    summary['maximum'] = np.max(x)
    return summary

first_column = bunchobject.data[:,[1]]
print(five_number_summary(first_column))

{'minimum': 9.71, 'first quartile': 16.17, 'median': 18.84, 'third quartile': 21.8, 'maximum': 39.28}


In [32]:
col_no = [0,1,2]
some_columns = bunchobject.data[:,col_no]
print( five_number_summary(some_columns) )

{'minimum': 6.981, 'first quartile': 14.45, 'median': 19.8, 'third quartile': 75.1, 'maximum': 188.5}


In [35]:
def normalize_minmax(data):
    return (data-np.min(data))/(np.max(data)-np.min(data))

In [36]:
first_column = bunchobject.data[:,[1]]
first_column_norm = normalize_minmax(first_column)
print(five_number_summary(first_column_norm))

{'minimum': 0.0, 'first quartile': 0.21846466012850865, 'median': 0.30875887724044637, 'third quartile': 0.40886033141697664, 'maximum': 1.0}


In [37]:
cols = [1, 7]
some_columns = bunchobject.data[:,cols]
snorm = normalize_minmax(some_columns)
print('normalized', five_number_summary(snorm))

normalized {'minimum': 0.0, 'first quartile': 0.0008541242362525458, 'median': 0.12616089613034626, 'third quartile': 0.4795697556008147, 'maximum': 1.0}
